### ISSUE TITLE
New branch codegen (matlab code generator)

### ISSUE THREAD

**Issue by kupiqu** [jsherfey/dnsim#10]
Using matlab code generator accelerates the simulation time in matlab significantly, by automatically generating a mex file. However:
1. creating the mex file takes time
2. codegen cannot support all matlab functions but only some restricted part of them (it can report errors at execution time)
3. it may not be available (e.g.toolbox missing or under Octave)

In order to make the implementation of codegen more efficient we will have to think how we can reuse previous mex files (assumed a same model is in place, but with tolerance for different parameter values).

We also need to somehow 'predict' if codegen is not going to work (for instance checking for a list of unsupported functions), and then:disable it/inform about possible solutions, if any.

There is a new branch dnsim_codegen explicitly about this feature in the code.

**Comment by kupiqu** [comment]
I would highly recommend to include current version of codegen in master/dev (although disabled by default with coder = 0 in current runsim.m).

The reason is that Jason is going to modify lots of things and it will be very hard to add codegen afterwards...

**Comment by kupiqu** [comment]
I removed my previous pull request and created a new one (pull request #12) according to the comment above

**Comment by kupiqu** [comment]
In addition to the model specification that is currently implemented, we need to load initial conditions as well, so a mex file doesn't depend on those.

**Comment by jsherfey** [comment]
created params.mat file that is read to set params and initial conditions in mex file. mex file does not change if parameters change. exception: # cells changes the size of the initial condition vector and codegen cannot properly declare variable size arrays.
