### ISSUE TITLE
Function handle `Iext` in `<simulation-data-file>.parms.biosim.Iext` prevents export of data file to JSON file

### ISSUE THREAD

**Issue by asoplata** [jsherfey/dnsim#5]
Problem: After loading a simulation data file into struct variable `foo`, when I try to export `foo` into JSON using JSONlab's `savejson()` function, it is unable to export the struct. This appears to be due to that it doesn't know how to interpret `foo.parms.biosim.Iext` (that's an I as in "eye"), which is a function handle, into a JSON-acceptable type. If you remove it e.g. via `foo.parms.biosim = rmfield(foo.parms.biosim, 'Iext')`, then it does export succesfully, and you can save it into a JSON file with `savejson('',foo,'foo-file.json')`.

Suggested solution: Simply remove all mention of `Iext` from the code. It does NOT appear to be used AT ALL in any functioning code, save for getting passed around as a parameter, in files `dnsim/matlab/functions`: `biosimdriver.m`, `biosim.m`, `runsim.m`, and `simdriver.m`. Except for when it is passed, I can't find any instance where it is used. This implies that it is either archaic and can be deleted, or its functionality has lapsed and is currently not included in the code. Either way, since all the places where it is used in the commented-out sections is still present in the git history and is thus recoverable, all usage of it could be deleted right now, which would enable full JSON export of new simulation data files.

**Comment by jsherfey** [comment]
Iext is archaic and no longer used. I have now removed it from the dnsim functions listed above (biosimdriver.m, biosim.m, runsim.m, simdriver.m).
