### ISSUE TITLE
The default reversal potential for an inhibitory synapse is 0 mV?

### ISSUE THREAD

**Issue by jchartove** [jsherfey/dnsim#54]
That is not what "inhibitory" means and now I am very sad that all this work I did was not with an I to I network at all. I will fix it, I just wanted to complain to you guys first (and alert people in case they were making the same mistake).

**Comment by jchartove** [comment]
Realized that that wasn't what the "i" stood for. Welp

**Comment by asoplata** [comment]
Was this related to a specific inhibition mechanism file? What is the 'I' in this context?

**Comment by jsherfey** [comment]
I think "i" refers to the ion current, as in "iAMPA.txt". The default
reversal potential for "iSYN.txt" corresponds to that for excitatory
synapses.

**Comment by jchartove** [comment]
What Jason said. I thought the "i" stood for "inhibitory."
